# REMOVE COMMENT FROM A C FILE.

#		ALGORITHM
#STEP 1 -> READ THE FILE.
#STEP 2 -> DELETE THE MULTI LINE COMMENT 1ST . THEN DELETE SINGLE LINE COMMENT . THEN DELETE THE COMMENT WRITTEN JUST AFTER CODE.
#STEP 3 -> PRINT THE FILE.

# sed -i IS USED. THIS WILL DELETE THE COMMENT DIRECTLY IN THE FILE


file=$1

s="\/\*"				# SETTING VARIABLE TO CHECK FOR /*
e="\*\/"				# SETTING VARIABLE TO CHECK FOR */  

sed -i "/$s/,/$e/d" $file  		# DELETING THE MULTI LINE COMMENT BETWEEN /**/
sed -i '/^\//d' $file 			# DELETING THE SINGLE LINE COMMENT AFTER //
sed -i "s/[\t]*\/\/.*$//" $file		# DELETING THE COMMENT AFTER THE CODE. IT WILL DELETE COMMENT ADJACENT TO CODE.


cat $file				# PRINTING THE FILE AGAIN
